#!/bin/bash
# Kommentar
# mkgmap --gmapsupp --mapname=13371337 --style-file=/home/christian/Dokumente/paint-the-town-red/styles/pttr -c split/template.args --output-dir=/home/christian/Dokumente/paint-the-town-red/garmin --description="Paint the Town Red"

mkgmap -c /home/christian/Dokumente/paint-the-town-red/run_options /home/christian/Dokumente/paint-the-town-red/pttr.typ


